name: involt
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Persistence & Data Modeling
  drift: ^2.16.0
  sqlite3_flutter_libs: ^0.5.20
  path_provider: ^2.1.2
  path: ^1.9.0
  
  # API & Serialization
  protobuf: ^3.1.0
  connectrpc: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  
  # Code Generation
  drift_dev: ^2.16.0
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
