-- Migration: Sync readings table with schema
-- Date: 2026-05-03

ALTER TABLE readings ADD COLUMN IF NOT EXISTS period_start DATE NOT NULL DEFAULT CURRENT_DATE;
ALTER TABLE readings ADD COLUMN IF NOT EXISTS period_end DATE NOT NULL DEFAULT CURRENT_DATE;
ALTER TABLE readings ADD COLUMN IF NOT EXISTS mantenimiento DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE readings ADD COLUMN IF NOT EXISTS adjustment DOUBLE PRECISION DEFAULT 0;
ALTER TABLE readings ADD COLUMN IF NOT EXISTS subtotal DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE readings ADD COLUMN IF NOT EXISTS round_difference DOUBLE PRECISION DEFAULT 0;
ALTER TABLE readings ADD COLUMN IF NOT EXISTS previous_balance DOUBLE PRECISION DEFAULT 0;
ALTER TABLE readings ADD COLUMN IF NOT EXISTS overdue_total DOUBLE PRECISION DEFAULT 0;
ALTER TABLE readings ADD COLUMN IF NOT EXISTS expiration_date DATE NOT NULL DEFAULT CURRENT_DATE;

-- Optional: remove defaults after adding columns if you want strictness
-- ALTER TABLE readings ALTER COLUMN period_start DROP DEFAULT;
-- ...
